name: actions_docker_ghcr
description: A Github action for building a Docker image and pushing to Github Container Registry
branding:
  icon: "check-circle"
  color: "green"
inputs:
  registry:
    description: "Docker registry to push image to"
    required: False
    default: "ghrc.io"
  image_name:
    description: "Name of docker image"
    required: False
    default: ${{ github.repository }}
  username:
    description: "username used to log into Docker registry"
    required: False
    default: ${{ github.actor }}
  password:
    description: "password (or token) used to log into Docker registry"
    required: True

runs:
  using: "composite"
  steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ inputs.password }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
